#coding=utf-8
import pymysql
conn=pymysql.connect(host='localhost',user='root',passwd='1',db='zelin',port=3306,charset='utf8')
type1=input('type sname:')
type2=input('type ssex:')
type3=input('type college:')
type4=input('type tel:')
cur=conn.cursor()
cur.execute("insert into student values(null,'%s','%s','%s','%s')"%(type1,type2,type3,type4))
cur.execute("insert into study (sid,sname) values ((select sid from student where sname='%s'),'%s')"%(type1,type1))
cur.execute("insert into job (sid,sname) values ((select sid from student where sname='%s'),'%s')"%(type1,type1))
cur.execute("insert into hopping (sid,sname) values ((select sid from student where sname='%s'),'%s')"%(type1,type1))
conn.commit()
cur.close()
conn.close()	
